package string;

import java.util.HashMap;

public class JQGridMethod {
	public String toCamelCase(String s) {
		String[] parts = s.split("_");
		String camelCaseString = "";
		int i = 0;
		for (String part : parts) {
			camelCaseString = camelCaseString + toProperCase(part, i);
			i++;
		}
		return camelCaseString;
	}

	public String toProperCase(String s, int i) {
		if(i==0){
			return s.toLowerCase();	
		}else{
			return s.substring(0, 1).toUpperCase() + s.substring(1).toLowerCase();
		}
		
	}
	
	public HashMap<String , String> words(){
		HashMap<String , String> map = new HashMap<String , String>();
		map.put("CONFIRM", "확인");
		map.put("ABBR_NM", "단축명");
		map.put("ABBREVIATION", "약어");
		map.put("ACC_TRNAS_YN", "회계이관여부");
		map.put("ACCEPTOR", "인수자");
		map.put("ACCEPTOR_ADDR", "인수자주소");
		map.put("ACCIDENT_AMT", "사고량");
		map.put("ACCIDENT_CBM", "사고용적");
		map.put("ACCIDENT_CD", "사고코드");
		map.put("ACCIDENT_MIW", "사고");
		map.put("ACCIDENT_NTFY_FLG", "사고통지식별");
		map.put("ACCIDENT_PKG_QTY", "사고수량");
		map.put("ACCIDENT_RCV", "반입사고");
		map.put("ACCIDENT_TYPE", "사고구분");
		map.put("ACCIDENT_WT", "사고중량");
		map.put("ACCOUNT_DATE", "회계이관일자");
		map.put("ACCOUNT_RCV", "미수금");
		map.put("ACHANGE_DATE", "취하일자");
		map.put("ACPT_YN", "허용");
		map.put("ACT_CBM", "CFS CBM");
		map.put("ACT_LOC", "층 존 단 행 열");
		map.put("ACT_SHIPPER", "CO-LOADER");
		map.put("ACTION_DATE", "조치일자");
		map.put("ACTUAL_AMOUNT", "실공급가액");
		map.put("ACTUAL_SHPR_MIW", "실화주");
		map.put("ACTUAL_SHPR_NM", "실화주명");
		map.put("ADDR", "주소");
		map.put("ADDR_1", "주소1");
		map.put("ADDR_2", "주소2");
		map.put("ADDR_3", "주소3");
		map.put("ADDROW", "행추가");
		map.put("ADJ_IVT_CBM", "수정용적");
		map.put("ADJ_IVT_PKG_QTY", "수정수량");
		map.put("ADJ_IVT_WT", "수정중량");
		map.put("ADJ_TYPE", "수정구분");
		map.put("ADJUSTMENT", "수정");
		map.put("ADV_PAY_BALANCE", "전도금 잔금");
		map.put("AG_CD", "ETB대행사 코드");
		map.put("AG_NM", "ETB대행사 명");
		map.put("AGENCY_CD", "대행사코드");
		map.put("AGENCY_NM", "대행사명");
		map.put("AGENT_CODE", "대리점 코드");
		map.put("AGENT_ID", "대리점 ID");
		map.put("AIR", "항공");
		map.put("AIR_INBND_MIW", "항공수입");
		map.put("AIR_OUTBND_MIW", "항공수출");
		map.put("ALL", "전체");
		map.put("ALLOC_CBM", "할당용적");
		map.put("ALLOC_MIW", "할당");
		map.put("ALLOC_QTY", "할당개수");
		map.put("ALLOC_WT", "할당중량");
		map.put("AMOUNT", "외화금액");
		map.put("AMOUNT_MIW", "금액");
		map.put("AMOUNT_MRN", "총합금액");
		map.put("AMOUNT_TOTAL", "공급가액 계");
		map.put("APLY_BATCH", "일괄반영");
		map.put("APPLY", "적용");
		map.put("APPLY_RATE_MIW", "요율적용");
		map.put("APPRAISE_AMT", "감정가액");
		map.put("APPRAISE_RATE", "감정료");
		map.put("APPROVAL_CBM", "승인용적");
		map.put("APPROVAL_DATE", "승인일자");
		map.put("APPROVAL_LAST_SHIP_INSR", "승인건 최종반출시 보험료");
		map.put("APPROVAL_MIW", "승인");
		map.put("APPROVAL_NO", "승인번호");
		map.put("APPROVAL_PKG_QTY", "승인수량");
		map.put("APPROVAL_QTY", "승인잔량");
		map.put("APPROVAL_RECV_PKG_QTY", "승인반입수량");
		map.put("APPROVAL_RECV_WT", "승인반입중량");
		map.put("APPROVAL_WT", "승인중량");
		map.put("APPROVED_AMT", "승인량");
		map.put("APR", "4월");
		map.put("AR_AP_TYPE", "매출/매입구분");
		map.put("AR_BILL_PROFIT", "매출대 청구실적서");
		map.put("AR_DATE", "매출일자");
		map.put("AR_GOODS", "보세/내국 화물");
		map.put("AR_INVOICE_CONT", "매출대 계산서발행내역");
		map.put("AR_MIW", "매출");
		map.put("AR_NO", "매출번호");
		map.put("AR_PKG_QTY", "매출개수");
		map.put("AR_REG_MIW", "매출등록");
		map.put("AR_ROWS", "매출건수");
		map.put("AR_SEQ_NO", "매출번호 (순번)");
		map.put("AR_TYPE", "보세/내국 구분");
		map.put("AR_WT", "매출중량");
		map.put("AR_YYYY", "매출번호 (년도)");
		map.put("ARRIVAL_CNT", "도착개수");
		map.put("ARRIVAL_DATE", "입항일");
		map.put("ARRIVAL_PLACE", "도착지");
		map.put("ARRIVAL_YMD", "입항년월일");
		map.put("ARTICLE", "기사");
		map.put("ASSIGN", "소속");
		map.put("AUG", "8월");
		map.put("AUTHORIZATION", "결재");
		map.put("AUTO_PICKING_APPLY", "자동피킹 적용");
		map.put("AUTONUM_SEQ_NM", "자동번호채번유형명");
		map.put("AUTONUM_SEQ_TYPE", "자동번호채번유형");
		map.put("BALANCE", "잔액");
		map.put("BARCODE_LIST", "바코드리스트");
		map.put("BASE_DATE", "기준일자");
		map.put("BASIC_MIW", "기본");
		map.put("BASIC_RATE", "기본단가");
		map.put("BASIS_S", "종량기본");
		map.put("BASIS_S_FRT_CD", "종량기본 운임코드");
		map.put("BASIS_V", "종가기본");
		map.put("BASIS_V_FRT_CD", "종가기본 운임코드");
		map.put("BEF_STOCK_AMT", "전일재고량");
		map.put("BIA_TEXT", "반입확인(BIA)→Text");
		map.put("BIB_TEXT", "반입확인(BIB)→Text");
		map.put("BILL_AMOUNT", "청구금액");
		map.put("BILL_CUST_ID", "청구처 ID");
		map.put("BILL_DATE", "정산일자");
		map.put("BILL_ISSUED", "계산서발행");
		map.put("BILL_MIW", "정산");
		map.put("BILL_NO", "정산번호");
		map.put("BILL_UNISSUED", "계산서미발행");
		map.put("BILL_UNISSUED_AMT", "계산서미발행금액");
		map.put("BILLING_CUST", "청구처");
		map.put("BILLING_CUST_CD", "청구처 코드");
		map.put("BILLING_CUST_NM", "청구처 명");
		map.put("BILLING_DATE", "청구일자");
		map.put("BKG_NO", "Booking No.");
		map.put("BL", "B/L NO.");
		map.put("BL_DIVIDE_MIW", "BL분할");
		map.put("BL_RETURN_REQUEST", "BL환원신청");
		map.put("BL_TYPE", "BL Type");
		map.put("BOA_TEXT", "반출확인(BOA)→Text");
		map.put("BONDED_AREA", "보세구역명칭");
		map.put("BONDED_AREA_MIW", "보세구역");
		map.put("BONDED_CARGO_INV_TXT_MIW", "보세화물재고→TXT");
		map.put("BONDED_CARGO_SPLIT_SHIPPING_MIW", "보세화물재고중분할반출→TXT");
		map.put("BONDED_GOODS", "보세화물");
		map.put("BONDED_GOODS_FIRE_INSURANCE_COND", "보세화물화재보험료 영수증상황보고");
		map.put("BONDED_GOODS_FIRE_INSURANCE_RCP", "보세화물 화재보험료 영수증 ||");
		map.put("BONDED_GOODS_FIRE_INSURANCE_SHIP_RPT", "보세화물화재보험 출고보고서");
		map.put("BONDED_HOME_RCV_EXCEPT", "통관후내국반입제외");
		map.put("BONDED_HOME_RCV_ONLY", "통관후내국반입만");
		map.put("BONDED_SHED", "장치");
		map.put("BONDED_SHIP", "통관반출");
		map.put("BONDED_SHIP_NO", "보세반출번호");
		map.put("BONDED_TRANS", "보세운송");
		map.put("BONDED_TRANS_NO", "보세운송번호");
		map.put("BONDED_TRANS_RCV", "보세운송반입");
		map.put("BONDED_TRANS_REGIST_NO", "보세운송신고번호");
		map.put("BONDED_TRANS_SHIP", "보세운송반출");
		map.put("BONDED_WH", "보세창고");
		map.put("BONDED_WH_INVENTORY_GOODS_LIST", "보세창고재고화물목록표");
		map.put("BONDED_YN", "통관여부");
		map.put("BOOKING_DATE", "Booking Date");
		map.put("BOOKING_NO", "Booking No.");
		map.put("BRANCH", "지점");
		map.put("BUYER_ATTN", "구매담당자");
		map.put("BUYER_ATTN_CD", "구매담당자코드");
		map.put("BUYER_ID", "구매자 ID");
		map.put("BUYER_NM", "구매자");
		map.put("BUYING", "BUYING");
		map.put("CALC_TYPE", "계산구분");
		map.put("CALC_WT_RND_AIR", "계산중량반올림(항공)");
		map.put("CALC_WT_RND_SEA", "계산중량반올림(해운)");
		map.put("CALC_WT_ROUND_AIR", "계산중량반올림(항공)");
		map.put("CALC_WT_ROUND_SEA", "계산중량반올림(해운)");
		map.put("CANCEL_DIVIDE", "분할취소");
		map.put("CALENDAR", "달력");
		map.put("CANCEL_DATETIME", "취소일시");
		map.put("CANCEL_TYPE", "취소구분");
		map.put("CARGO_AGREE_YN", "화물동의");
		map.put("CARGO_AMT_AMT", "종가료");
		map.put("CARGO_AMT_RATE", "종가율");
		map.put("CARGO_CD", "화물코드");
		map.put("CARGO_CLASS", "화물구분");
		map.put("CARGO_CLASS_N", "N:반입전");
		map.put("CARGO_CLASS_Y", "Y:반입후");
		map.put("CARGO_DELIVERY_AGREEMENT", "화물인도동의서");
		map.put("CARGO_LOC_MIW", "화물위치");
		map.put("CARGO_NM", "화물형태");
		map.put("CARGO_NO", "화물관리번호");
		map.put("CARGO_SHIP_ARLIST", "화물반출정산 LIST");
		map.put("CARGO_STATUS_CCD_1", "[예약]");
		map.put("CARGO_STATUS_CCD_2", "[반입]");
		map.put("CARGO_STATUS_CCD_3", "[반출]");
		map.put("CARGO_STATUS_CCD_4", "[마감]");
		map.put("CARGO_TYPE", "화물구분");
		map.put("CARGO_WT_AMT", "종량료");
		map.put("CARGO_WT_RATE", "종량율");
		map.put("CARR_CD", "선사부호");
		map.put("CARR_FWD", "이월");
		map.put("CARR_PLACE", "선회사");
		map.put("CARR_PORT", "선사항");
		map.put("CARRIER_NAME", "LINE");
		map.put("CASE", "건별");
		map.put("CB_CD", "관세사코드");
		map.put("CB_MIW", "관세사");
		map.put("CB_NM", "관세사 명");
		map.put("CBM", "용적");
		map.put("CBM_MRN", "총용적");
		map.put("CBM_REASON", "사고용적");
		map.put("CD", "코드");
		map.put("CD_NM", "코드명");
		map.put("CFS", "CFS");
		map.put("CFS_CBM", "CFS-CBM");
		map.put("CFS_HSN", "CFS HSN");
		map.put("CHANGE_CODE", "변환코드");
		map.put("CHANGE_MIW", "변경");
		map.put("CHANGE_TYPE", "변경구분");
		map.put("CHARGE_DAY", " 유료일수");
		map.put("CHK", "선택");
		map.put("CHM", "회장");
		map.put("CIPHER", "자릿수");
		map.put("CLASS_DIV", "분할구분");
		map.put("CLASS_WH", "창고구분");
		map.put("CLP_DATE", "CLP 일자");
		map.put("CLP_MIW", "CLP");
		map.put("CLP_NO", "CLP 번호");
		map.put("CLP_RPT_MIW", "CONTAINER LOAD PLAN");
		map.put("CNEE_ADDR_1", "수하인주소1");
		map.put("CNEE_ADDR_2", "수하인주소2");
		map.put("CNEE_ADDR_3", "수하인주소3");
		map.put("CNEE_CD", "실화주코드");
		map.put("CNEE_ID", "수하인");
		map.put("CNEE_MIW", "CNEE");
		map.put("CNEE_NM", "수하인상호");
		map.put("CNEE_RESIDENT", "수하인 사업자번호");
		map.put("CNEE_RGST", "수하인 사업자번호");
		map.put("CNEE_TEL", "수하인 전화번호");
		map.put("CNEE_TOORDER_NTFY_PRINT", "수하인이 TO ORDER일경우 통지처를 출력");
		map.put("CNTR_CD", "컨테이너 코드");
		map.put("CNTR_CNT", "컨테이너개수");
		map.put("CNTR_FREE", "컨테이너면제");
		map.put("CNTR_FRT_CD", "컨테이너 운임코드");
		map.put("CNTR_MIW", "컨테이너");
		map.put("CNTR_NO", "컨테이너 번호");
		map.put("CNTR_SEQ_NO", "순번");
		map.put("CNTR_TYPE", "컨테이너 유형코드");
		map.put("CODE", "코드번호");
		map.put("CODE_MAP", "코드맵핑");
		map.put("COLL_DATE", "수금일자");
		map.put("COLUMN_NO", "열");
		map.put("COMMODITY_CD", "상품코드");
		map.put("COMPANY", "소속사");
		map.put("COMPANY_NM", "상호");
		map.put("COMPARE_TARGET", "비교대상");
		map.put("COMPUTE_CONTENT", "산출내역");
		map.put("CON_SEL", "연장구분");
		map.put("CONFIRM_DATE", "확인일자");
		map.put("CONFIRMATION", "확인서");
		map.put("CONFIRMOR", "확인자");
		map.put("CONTACT_NO", "연락처");
		map.put("CONTAINER_RATE", "컨테이너료");
		map.put("CONTENT_MIW", "내용");
		map.put("CONTRACT_DATE", "계약일자");
		map.put("CONTRACT_NO", "계약번호");
		map.put("CONTRACT_TYPE", "계약유형");
		map.put("COPY", "복사");
		map.put("CORR_NOTI_MIW", "정정통보");
		map.put("CORRECTION_APPLY_DATE", "정정신청일자");
		map.put("CORRECTION_DATE", "정정일자");
		map.put("CORRECTION_MIW", "정정");
		map.put("CORRECTION_NO", "정정차수");
		map.put("CORRECTION_PERSON", "정정신청인");
		map.put("CORRECTION_REASON", "정정사유");
		map.put("CORRECTION_REASON1", "정정사유1");
		map.put("CORRECTION_REASON2", "정정사유2");
		map.put("CORRECTION_REQUESTOR", "정정신청인");
		map.put("CORRECTION_SEQ_NO", "정정차수");
		map.put("CORRECTION_TYPE", "정정구분");
		map.put("COUNT", "건수");
		map.put("CREATE_SEQ", "생성차수");
		map.put("CRT_SUBSCRIP", "계약청약서");
		map.put("CRT_TERM_DATE", "계약기간");
		map.put("CRT_TERM_DATE_FROM", "계약기간시작일");
		map.put("CRT_TERM_DATE_TO", "계약기간종료일");
		map.put("CURR_CD", "화폐코드");
		map.put("CURR_MIW", "화폐");
		map.put("CUST", "거래처");
		map.put("CUST_CD", "거래처코드");
		map.put("CUST_CLASS", "거래처구분");
		map.put("CUST_ID", "사업자 등록번호");
		map.put("CUST_NM", "거래처명");
		map.put("CUST_TYPE", "업체구분");
		map.put("CUSTOMS", "세관");
		map.put("CUSTOMS_DEP", "세관과");
		map.put("CUSTOMS_DOC_REGIST", "세관신고번호");
		map.put("CUSTOMS_INFO", "통관사항");
		map.put("CUSTOMS_PERSON", "세관담당자");
		map.put("CUSTOMS_SND", "세관전송번호");
		map.put("CUSTOMS_SND_SEQ_NO", "세관제출번호 (순번)");
		map.put("CUSTOMS_SND_YYYY", "세관제출번호 (년도)");
		map.put("CUTOFF_MIW", "절사");
		map.put("CY", "CY");
		map.put("DAILY_IN_CARGO_RCV_RPT", "일일 수입 화물 반입 보고서");
		map.put("DAILY_IN_CARGO_SHIP_RPT", "일일 수입 화물 반출 보고서");
		map.put("DAILY_SECURITY_DOC", "일일 담보원장");
		map.put("DAMEGE_QTY", "파손수량");
		map.put("DATE_FROM", "부터");
		map.put("DATE_MIW", "일자");
		map.put("DATE_TO", "까지");
		map.put("DAY", "일");
		map.put("DAY_RCV_PRT", "일일 반입보고서");
		map.put("DAY_SHIP_PRT", "일일 반출보고서");
		map.put("DC", "할인율");
		map.put("DC_CD", "할인코드");
		map.put("DC_NM", "할인명");
		map.put("DC_RATE", "할인율");
		map.put("DC_RATE_MIW", "할인료");
		map.put("DC_TYPE", "할증구분");
		map.put("DEAR", "귀하");
		map.put("DEC", "12월");
		map.put("DEL", "삭제");
		map.put("DELIVERY_ORDER", "출고지시서");
		map.put("DELROW", "행삭제");
		map.put("DEPARTURE_TYPE", "출발지 구분");
		map.put("DESC_MIW", "내역");
		map.put("DESCRIPTION", "설명");
		map.put("DEST", "멸각");
		map.put("DEST_DISUSE", "멸각 폐기");
		map.put("DISAPPROVAL_MIW", "미승인");
		map.put("DISUSE", "폐기");
		map.put("DIVIDE_CLASS", "분할구분");
		map.put("DIVIDE_LIST", "분할 리스트");
		map.put("DIVIDE_NO", "분할차수");
		map.put("DIVIDE_NO_RPT", "차수");
		map.put("DIVISION_CLASS", "신고유형");
		map.put("DIVISION_CLASS_1", "1:분할등록");
		map.put("DIVISION_CLASS_2", "2:분할취소");
		map.put("DIVISION_DATE", "신고일");
		map.put("DIVISION_YN", "신고여부");
		map.put("DM_CBM", "난태용적");
		map.put("DM_INSERT", "난태등록");
		map.put("DM_PKG_QTY", "난태개수");
		map.put("DM_SEARCH", "난태조회");
		map.put("DM_WT", "난태중량");
		map.put("DO_DOCUMENT_TYPE_MIW", "D/O 문서종류");
		map.put("DO_MIW", "D/O");
		map.put("DO_NO", "D/O번호");
		map.put("DO_VALID_PERIOD", "D/O유효일자");
		map.put("DO_YN", "D/O여부");
		map.put("DOC_APPROVE", "근거번호");
		map.put("DOC_FIX", "고정문구");
		map.put("DOC_FUN", "문서구분");
		map.put("DOC_NO", "근거번호");
		map.put("DOC_NOTICE", "문서공지");
		map.put("DOC_REGIST", "신고번호");
		map.put("DOC_SEL", "업무구분");
		map.put("DOC_SEQ_NO", "일련번호");
		map.put("DOC_TYPE", "업무구분");
		map.put("DOC_YYYY", "작업년도");
		map.put("DOCUMENT_TYPE_MIW", "문서종류");
		map.put("DOT_LINE", "절취선");
		map.put("DOWN_AMT", "하차료");
		map.put("DOWN_PORT", "항만하역");
		map.put("DOWN_RCV", "하차입고");
		map.put("DOWN_RCV_FRT_CD", "하차입고 운임코드");
		map.put("DUTY", "관세액");
		map.put("EDI_SEND_A_MIW", "접수송신");
		map.put("EDI_SEND_L_MIW", "반출확인송신");
		map.put("EMAIL", "이메일주소");
		map.put("EMAIL_FROM", "발신 이메일주소");
		map.put("EMAIL_TO", "수신 이메일주소");
		map.put("EMAIL_TO_1", "수신 이메일주소1");
		map.put("EMAIL_TO_2", "수신 이메일주소2");
		map.put("EMAIL_TO_3", "수신 이메일주소3");
		map.put("ENCLOSURE_3_FORM", "별지 제3호 서식");
		map.put("ENCLOSURE_4_FORM", "별지 제4호 서식");
		map.put("END_DATE", "종료일자");
		map.put("ENG", "영문");
		map.put("ENTERING_DATE", "입고일");
		map.put("ENTERING_NO", "입고번호");
		map.put("ERR_DESC", "오류내역");
		map.put("ERR_NOTI_MIW", "오류통보");
		map.put("ERR_RCV_DESC", "오류통보 수신내역");
		map.put("ERROR_FLG", "에러구분");
		map.put("EST_CBM", "예정용적");
		map.put("EST_MIW", "예정");
		map.put("EST_PKG_QTY", "예정수량");
		map.put("EST_QTY", "예정량");
		map.put("EST_STOCKPILE_DATE", "체화예정일자");
		map.put("EST_WT", "예정중량");
		map.put("ETA", "도착일자");
		map.put("ETA_DATE", "ETA");
		map.put("ETB", "전자세금계산서");
		map.put("ETB_ATTN", "담당자");
		map.put("ETB_CUST_ID", "사업자번호");
		map.put("ETB_DEPARTMENT", "부서");
		map.put("ETB_WH_CD", "식별코드");
		map.put("ETC", "기타");
		map.put("ETC_AMOUNT", "기타료공급가액");
		map.put("ETC_INVOICE_RATE", "기타료명세서");
		map.put("ETC_RATE", "기타료");
		map.put("ETC_VAT", "기타료세액");
		map.put("ETC_YN", "기타구분");
		map.put("ETD", "출발일자");
		map.put("ETD_DATE", "ETD");
		map.put("EX_RATE", "환율");
		map.put("EXA_AUTONUM", "자동번호(예제)");
		map.put("EXC_EXPECT_PRT", "수입화물반출입및체화량보고서");
		map.put("EXC_STAT", "반출입상황");
		map.put("EXCESS_AMT_MIW", "초과금액");
		map.put("EXCHANGE", "반출입");
		map.put("EXIST_SHIP_CBM", "기반출용적");
		map.put("EXIST_SHIP_QTY", "기반출수량");
		map.put("EXIST_SHIP_WT", "기반출중량");
		map.put("EXP_AMT_MIW", "지출금액");
		map.put("EXP_REG_MIW", "지출등록");
		map.put("EXPECT", "체화");
		map.put("EXPECT_DATE", "체화일자");
		map.put("EXPECT_DAY", "체화일수");
		map.put("EXPECT_MV", "체화이전");
		map.put("EXPECT_OCC_PROC_STAT", "체화발생 및 처리상황 보고서");
		map.put("EXPECT_QTY", "체화수량");
		map.put("EXPECT_WT", "체화중량");
		map.put("EXPIRATION_DATE", "유통기한");
		map.put("EXPT_MIW", "예정");
		map.put("EXTENT", "연장구분");
		map.put("EXTENT_DATE", "연장기한");
		map.put("EXTENT_NO", "연장근거");
		map.put("EXTRA", "할증율");
		map.put("EXTRA_CD", "할증코드");
		map.put("EXTRA_CHARGE", "정외요금");
		map.put("EXTRA_DESC", "상세내역");
		map.put("EXTRA_MIW", "Extra Rate");
		map.put("EXTRA_NM", "할증내역(축약내역)");
		map.put("EXTRA_RATE", "할증율");
		map.put("EXTRA_RATE_MIW", "할증료");
		map.put("EXTRA_S", "종량할증");
		map.put("EXTRA_S_FRT_CD", "종량할증 운임코드");
		map.put("EXTRA_TYPE", "할증구분");
		map.put("EXTRA_V", "종가할증");
		map.put("EXTRA_V_FRT_CD", "종가할증 운임코드");
		map.put("EXTRA_WT", "초과중량(KG)");
		map.put("FAX", "팩스번호");
		map.put("FEB", "2월");
		map.put("FILE_ATTCH_MIW", "File Attchment");
		map.put("FILE_MIW", "파일");
		map.put("FINAL_DESTINATION", "DEST");
		map.put("FINAL_MIW", "FINAL");
		map.put("FIND_NAME", "검색");
		map.put("FIRE_INSURANCE", "화재보험");
		map.put("FIRE_INSURANCE_BILL_MIW", "화재보험(정산)");
		map.put("FIRM", "상호");
		map.put("FOR_ASCA", "협회비본");
		map.put("FOR_SHPR", "화주용");
		map.put("FOREIGN_RCV", "외국에서 반입");
		map.put("FORMULA_CD", "계산식 코드");
		map.put("FREIGHT_SEARCH", "운임조회");
		map.put("FRI", "금");
		map.put("FRT_CD", "운임코드");
		map.put("FRT_NM", "운임명");
		map.put("FULL_NM", "전체명");
		map.put("FWD", "Forwarder");
		map.put("FWD_CD", "포워더코드");
		map.put("FWD_MIW", "포워더");
		map.put("FWD_NM", "포워더명");
		map.put("GENERAL_WH", "일반창고");
		map.put("GNRL_MIW", "일반");
		map.put("GOODS", "종목");
		map.put("GOODS_DATE", "입고일자");
		map.put("GOODS_TYPE", "내국물품");
		map.put("GRADE", "급");
		map.put("GRADE_NO", "급수");
		map.put("GROUP_ITEM", "그룹품목");
		map.put("GROUP_ITEM_CD", "그룹품목코드");
		map.put("GROUPING", "그룹지정");
		map.put("GUARD_WORKER", "경비근무자");
		map.put("HAZ", "위험화물");
		map.put("HAZ_1", "위험(특수)화물정보1");
		map.put("HAZ_2", "위험(특수)화물정보2");
		map.put("HAZ_3", "위험(특수)화물정보3");
		map.put("HDL", "취급자");
		map.put("HEIGHT", "높이");
		map.put("HIDE", "숨김");
		map.put("HOME", "내국");
		map.put("HOME_CARGO_RCV_RPT", "내국물품 일일 입고보고서");
		map.put("HOME_CARGO_SHIP_RPT", "내국물품 일일 출고보고서");
		map.put("HOMEPAGE", "홈페이지 주소");
		map.put("HOUR", "시");
		map.put("HOUSE_DO", "House D/O");
		map.put("HOUSE_DO_NO", "House D/O No.");
		map.put("HS", "HS코드");
		map.put("HSN", "HSN");
		map.put("IF_MSG", "IF 메시지");
		map.put("IF_STATUS", "IF 상태");
		map.put("IF_TRC_SCD", "IF 추적상태코드");
		map.put("IMAGE_NM", "이미지");
		map.put("IMP_CARGO_LABEL_PRINT_TITLE", "수 입 화 물 품 목 카 드");
		map.put("IMP_CARGO_LBL_BARCODE", "수입화물표(바코드전용프린터)");
		map.put("IMP_CARGO_LBL_PRT", "수입화물표");
		map.put("IMP_OUTBND_CARGO_CRT_SCR", "수입수출화물 계약청약서");
		map.put("IMPORT", "수입");
		map.put("IMPORT_BONDED", "수입통관");
		map.put("IMPORT_REGIST_DATE", "수입신고기한");
		map.put("IMPORT_REGIST_NO", "수입신고번호");
		map.put("IN_DATE", "입력일자");
		map.put("IN_PERSON", "입력자");
		map.put("IN_TIME", "입력시간");
		map.put("INCOTEMS", "인도조건");
		map.put("INNER_TYPE_MIW", "내부용");
		map.put("INPUT_AMT", "입력금액");
		map.put("INPUT_QTY_MIW", "입고QTY");
		map.put("INPUT_SEQ_NO", "입력순번");
		map.put("INS_ADD_YN", "보험료증감여부");
		map.put("INS_ASCA", "손해보험협회");
		map.put("INS_ASCA_BONDED_GOODS_FIRE_INSURANCE_CPTR", "대한손해보험협회 보세화물화재보험 전산용");
		map.put("INS_CRT_NM", "보험계약자");
		map.put("INS_EDI_YN", "보험전송구분");
		map.put("INS_ENTRANCE", "보험가입액");
		map.put("INS_TOT_RATE", "보험료총계");
		map.put("INS_TOTAL_RATE", "보험료포함총액");
		map.put("INS_TOTLA_RATE", "보험료포함총액");
		map.put("INSPECTION", "검수");
		map.put("INSPECTION_DATE", "검수일자");
		map.put("INSPECTION_ENGINE", "검색기");
		map.put("INSPECTION_NO", "미검수건");
		map.put("INSPECTION_SEAL", "검사봉인");
		map.put("INSPECTION_TYPE", "검사구분");
		map.put("INSPECTION_YES", "검수건");
		map.put("INSPECTION_YN", "검사대상");
		map.put("INSR_FREE", "보험료면제");
		map.put("INSURANCE_COND", "영수증현황");
		map.put("INSURANCE_DAY", "보험일");
		map.put("INSURANCE_FREE", "보험료면제구분");
		map.put("INSURANCE_FRT_CD", "보험 운임코드");
		map.put("INSURANCE_MONTH_DAY", "보험월일");
		map.put("INSURANCE_RATE", "보험료");
		map.put("INSURANCE_RATE_DATE", "보험요율번호");
		map.put("INSURANT", "피보험자");
		map.put("INVENTORY", "재고");
		map.put("INVENTORY_BASE_DATE", "재고기준일");
		map.put("INVENTORY_BYITEM", "재고(항목별)");
		map.put("INVENTORY_CBM", "재고용적");
		map.put("INVENTORY_GENRL", "재고(일반)");
		map.put("INVENTORY_PKG_QTY", "재고수량");
		map.put("INVENTORY_QTY", "재고잔량");
		map.put("INVENTORY_WT", "재고중량");
		map.put("INVOICE", "거래명세서");
		map.put("INVOICE_01_TITLE", "보관료 및 작업료 명세서");
		map.put("INVOICE_DATE", "거래명세일자");
		map.put("INVOICE_MIW", "Invoice");
		map.put("INVOICE_NO", "거래명세서번호");
		map.put("IO", "수입/수출 구분");
		map.put("IO_CARGO_RCV_RPT", "일일수출(입)화물반입보고서");
		map.put("IO_CARGO_SHIP_RPT", "일일수출(입)화물반출보고서");
		map.put("IO_CCD", "수출입");
		map.put("ISSUE_DATE", "발급일자");
		map.put("ISSUED_AMT", "발행금액");
		map.put("ISSUED_CUST", "발급업체");
		map.put("ISSUED_DATE", "발행일자");
		map.put("ISSUED_DO_CUST", "D/O발행업체");
		map.put("ISSUED_MIW", "발행");
		map.put("ISSUED_TIME", "발행시간");
		map.put("ITEM", "품목");
		map.put("ITEM_1", "품목1");
		map.put("ITEM_2", "품목2");
		map.put("ITEM_3", "품목3");
		map.put("ITEM_CD", "품목코드");
		map.put("ITEM_EN", "품목명(영문)");
		map.put("ITEM_HS", "품목코드(HS)");
		map.put("ITEM_KO", "품목명(한글)");
		map.put("ITEM_MIW", "항목");
		map.put("ITEM_NM", "품명");
		map.put("ITEM_NM_ENG", "품명(영)");
		map.put("ITEM_NO", "품목번호");
		map.put("ITEM_PKG_CD", "품목포장단위");
		map.put("ITEM_SEARCH", "품목조회");
		map.put("JAN", "1월");
		map.put("JOB_TYPE", "업무구분");
		map.put("JUL", "7월");
		map.put("JUN", "6월");
		map.put("KIND", "업태");
		map.put("LANG", "언어");
		map.put("LANG_CD", "언어코드");
		map.put("LAPSE", "체화율(%)");
		map.put("LAST_MONTH", "전월");
		map.put("LAST_MONTH_CARR_FWD", "전월 이월");
		map.put("LAST_MONTH_INVENTORY", "전월재고");
		map.put("LC_YN", "L/C여부");
		map.put("LCC_APLY_UNIT_CD", "물류비 적용 단위 코드");
		map.put("LEN_MIW", "가로");
		map.put("LENGTH", "길이");
		map.put("LEVY", "감정가격");
		map.put("LICENS_CBM", "면장용적");
		map.put("LICENS_NO", "면장번호");
		map.put("LICENS_PKG_QTY", "면장수량");
		map.put("LICENS_WT", "면장중량");
		map.put("LOAD_PORT", "적재항");
		map.put("LOAD_VESSEL", "적재선명");
		map.put("LOC", "실제 location");
		map.put("LOC_CD", "위치코드");
		map.put("LOC_CERTI", "장치확인번호");
		map.put("LOC_LST", "최종목적지(장치장코드)");
		map.put("LOC_NM", "위치명");
		map.put("LOC_OUT", "발송지");
		map.put("LOC_PLACE", "장치위치");
		map.put("LOC_PORT", "입항지");
		map.put("LOC_TYPE", "위치구분");
		map.put("LOCAL_AMOUNT", "자국금액");
		map.put("LOCAL_AR_MIW", "내국매출");
		map.put("LOCAL_CARGO_INV_TXT_MIW", "내국화물재고→TXT");
		map.put("LOCAL_GOODS", "내국화물");
		map.put("LOCAL_RCV_MIW", "내국반입");
		map.put("LOCAL_SHIP_MIW", "내국반출");
		map.put("LOFT_YN", "현도여부");
		map.put("LOG_DATETIME", "로그일시");
		map.put("LOG_DESC", "로그내용");
		map.put("LOG_ID", "로그ID");
		map.put("LOL", "현지어");
		map.put("LOT_NO", "제조번호");
		map.put("MAKE_TERM", "작성기간");
		map.put("MANIFEST_NOTIFY", "적하목록상의 Notify");
		map.put("MAR", "3월");
		map.put("MARK", "기호");
		map.put("MASTER_DO", "Master D/O");
		map.put("MASTER_DO_NO", "Master D/O No.");
		map.put("MAX_COL", "최대행");
		map.put("MAX_NO", "최대일련번호");
		map.put("MAX_ROW", "최대열");
		map.put("MAX_WEIGTH", "최대중량");
		map.put("MAY", "5월");
		map.put("MEASURE_RATE", "검척료");
		map.put("MEASUREING", "Measureing");
		map.put("MENU_ID", "메뉴ID");
		map.put("MENU_LEVEL", "Menu Level");
		map.put("MENU_NM", "메뉴명");
		map.put("MINUTE", "분");
		map.put("MNGMT_NO", "관리번호");
		map.put("MNT_UNIT", "원정");
		map.put("MOBILE_NO", "핸드폰번호");
		map.put("MODEL_NO", "모델번호");
		map.put("MON", "월");
		map.put("MONTH", "월");
		map.put("MONTH_IO_CCD_EXC_STAT", "월간수(출)입화물반출입현화");
		map.put("MONTH_IO_CCD_STAT", "월별수출입통계");
		map.put("MONTHS", "개월");
		map.put("MRN", "MRN");
		map.put("MSG_DESC", "메세지 설명");
		map.put("MSG_ID", "메세지ID");
		map.put("MSN", "MSN");
		map.put("MSN_MIW", "MSN/HSN");
		map.put("NACC_KRR", "가육양식별");
		map.put("NAME", "성명");
		map.put("NAME_MIW", "명칭");
		map.put("NET_PRICE", "원가");
		map.put("NET_WT", "총순중량");
		map.put("NET_WT_UNIT", "총순중량단위");
		map.put("NEW_HSN", "신규 HSN");
		map.put("NEW_LOC_NM", "새위치명");
		map.put("NEW_LOC_PLACE", "새위치명");
		map.put("NM", "명");
		map.put("NO", "번호");
		map.put("NO_ARRAY", "번호구성배열");
		map.put("NO_MIW", "번호");
		map.put("NO_PAY", "미수");
		map.put("NO_TEMPINV", "임시거래명세서번호");
		map.put("NON_REGI", "미등록");
		map.put("NOT", "아니오");
		map.put("NOTE_FLG", "보고상태");
		map.put("NOTI", "알림");
		map.put("NOTICE", "보고상태");
		map.put("NOTICE_COUNT", "고시회수");
		map.put("NOTICE_DATE", "통보일자");
		map.put("NOTICE_DATETIME", "통보일시");
		map.put("NOTICE_FLG", "체화여부");
		map.put("NOTICE_FUN", "통지구분");
		map.put("NOTICE_OVER_PKG_QTY", "체화수량");
		map.put("NOTICE_OVER_WT", "체화중량");
		map.put("NOTICE_PKG_QTY", "통보수량");
		map.put("NOTICE_TYPE", "통고구분");
		map.put("NOTICE_WT", "통보중량");
		map.put("NOTICE_YESNO", "체화구분");
		map.put("NOV", "11월");
		map.put("NTFY_ADDR_1", "통지처주소1");
		map.put("NTFY_ADDR_2", "통지처주소2");
		map.put("NTFY_ADDR_3", "통지처주소3");
		map.put("NTFY_FLG", "통지식별");
		map.put("NTFY_ID", "통지처");
		map.put("NTFY_NM", "통지처명");
		map.put("NTFY_PLACE", "통지선");
		map.put("NTFY_TEL", "통지처 전화번호");
		map.put("OCC", "발생");
		map.put("OCT", "10월");
		map.put("OPEN_INSPECTION", "개장검사");
		map.put("OPERATE_APPLY_AIR", "작업료 항공요율로 적용여부");
		map.put("OPERATE_APPLY_SEA", "작업료 해운요율로 적용여부");
		map.put("OPERATE_CALC_TYPE", "작업료계산식구분");
		map.put("OPERATE_CALC_WT", "작업계산중량");
		map.put("OPERATE_CNTR_FREE", "컨테이너료면제구분");
		map.put("OPERATE_DC", "작업료할인%");
		map.put("OPERATE_EXTRA", "작업료할증%");
		map.put("OPERATE_EXTRA_CD_1", "작업료할증코드(하차)");
		map.put("OPERATE_EXTRA_CD_2", "작업료할증코드(상차)");
		map.put("OPERATE_FREE", "작업료면제구분");
		map.put("OPERATE_RATE_DATE", "작업요율번호");
		map.put("OPERATOR", "연산자");
		map.put("OPRATION_AMOUNT", "작업료공급가액");
		map.put("OPRATION_RATE", "작업료");
		map.put("OPRATION_RATE_TOTAL", "작업료 계");
		map.put("OPRATION_VAT", "작업료세액");
		map.put("OPRT_CNTR_FREE", "컨테이너면제");
		map.put("OPRT_DC", "작업료할인");
		map.put("OPRT_EXTRA", "작업료할증");
		map.put("OPRT_INVOICE_RATE", "작업료명세서");
		map.put("OPRT_RATE_TOTAL", "작업료총계");
		map.put("ORDER_DATE", "주문일자");
		map.put("ORDER_NO", "주문번호");
		map.put("ORDER_TYPE", "주문유형");
		map.put("ORIGIN_CD", "원산지코드");
		map.put("ORIGIN_MIW", "원산지");
		map.put("ORIGINAL_MIW", "원본");
		map.put("OUTBND", "수출");
		map.put("OUTBND_MNGMT_NO", "수출관리번호");
		map.put("OUTBND_REGIST_SHED", "수출 신고 장치");
		map.put("OUTER_TYPE_MIW", "외부용");
		map.put("OVER", "이상");
		map.put("PACK_MIW", "Packing List");
		map.put("PACKING_CBM", "포장용적");
		map.put("PACKING_DATE", "포장일자");
		map.put("PACKING_LIST", "Item List");
		map.put("PACKING_NO", "포장번호");
		map.put("PACKING_QTY", "포장개수");
		map.put("PACKING_WT", "포장중량");
		map.put("PAGE", "페이지");
		map.put("PAID_DATE", "지불일자");
		map.put("PAPER", "용지");
		map.put("PASSED_CBM", "통과용적");
		map.put("PASSED_PKG_QTY", "통과수량");
		map.put("PASSED_WT", "통과중량");
		map.put("PAY", "입금");
		map.put("PAY_CERT", "납입증명서");
		map.put("PAY_CUST_ID", "지불처 코드");
		map.put("PAY_CUST_NM", "지불처명");
		map.put("PAYMENTS_MIW", "결제금액");
		map.put("PERSON", "신청자");
		map.put("PERSON_CD", "신청인상호코드");
		map.put("PERSON_NM", "신청인상호명");
		map.put("PERSON_REASON", "신청사유");
		map.put("PERSON_TEL", "신청인전화번호");
		map.put("PERSON_TYPE", "신청자구분");
		map.put("PERSON_TYPE_1", "1:화주(대리인)");
		map.put("PERSON_TYPE_2", "2:보세구역");
		map.put("PHYSICAL_INSPECTION", "현품확인사항");
		map.put("PICKING_CBM", "피킹용적");
		map.put("PICKING_DATE", "Picking일자");
		map.put("PICKING_MIW", "피킹");
		map.put("PICKING_NO", "Picking번호");
		map.put("PICKING_ORDER", "Picking지시서");
		map.put("PICKING_QTY", "피킹개수");
		map.put("PICKING_SEQ_NO", "피킹순번");
		map.put("PICKING_WT", "피킹중량");
		map.put("PKG_CBM", "포장용적");
		map.put("PKG_CD", "포장단위");
		map.put("PKG_KINDS", "포장종류");
		map.put("PKG_MIW", "포장");
		map.put("PKG_NO", "포장번호");
		map.put("PKG_QTY", "수량");
		map.put("PKG_QTY_MRN", "총포장개수");
		map.put("PKG_QTY_REASON", "사고수량");
		map.put("PKG_TYPE", "포장유형");
		map.put("PKG_WEIGHT", "포장중량");
		map.put("PLACE", "장소");
		map.put("PO_NO", "구매주문번호");
		map.put("POD_CD", "도착지코드");
		map.put("POD_MIW", "Place Of Delivery");
		map.put("POD_NM", "도착지명");
		map.put("POL_MIW", "Port Of Loading");
		map.put("POR_MIW", "Place Of Receipt");
		map.put("PORT_CD", "입항지 코드");
		map.put("PORT_NM", "입항지 명");
		map.put("POST_NO", "우편번호");
		map.put("PRE_RCV_MIW", "선입고");
		map.put("PREMIUM_RATE", "보험요율");
		map.put("PRESIDENT", "대표자");
		map.put("PRESIDENT_NM", "대표자");
		map.put("PRGS_MIW", "진행상태");
		map.put("PRGS_STATUS_MIW", "진행상황");
		map.put("PRINT_DATE", "출력일");
		map.put("PRINTING", "인쇄");
		map.put("PROC_KIND", "처리구분");
		map.put("PROCESSING", "처리");
		map.put("PROCESSING_STATUS", "처리상태");
		map.put("PROFIT_DATE", "실적일자");
		map.put("PRT_CNT_MIW", "매");
		map.put("PUB_SALE", "공매");
		map.put("QTY_MRN", "총수량");
		map.put("RACK_MAX_COL", "렉 최대행");
		map.put("RACK_MAX_ROW", "렉 최대열");
		map.put("RACK_NO", "렉번호");
		map.put("RANGE_FROM", "시작범위");
		map.put("RANGE_TO", "종료범위");
		map.put("RATE", "요율");
		map.put("RATE_1", "보통1급");
		map.put("RATE_10", "위험야적");
		map.put("RATE_2", "보통2급");
		map.put("RATE_3", "보통3급");
		map.put("RATE_4", "보통4급");
		map.put("RATE_5", "보통야적");
		map.put("RATE_6", "위험1급");
		map.put("RATE_7", "위험2급");
		map.put("RATE_8", "위험3급");
		map.put("RATE_9", "위험4급");
		map.put("RATE_CD", "요율코드");
		map.put("RATE_DATE", "요율적용일");
		map.put("RATE_DAY", "적용일");
		map.put("RATE_MONTH", "적용월");
		map.put("RATE_NM", "내역");
		map.put("RATE_TYPE", "요율구분(KG)");
		map.put("RATE_UNIT", "요율단위");
		map.put("RCV_A", "반입확인(BIA)");
		map.put("RCV_AGREE_DOC", "반입승인");
		map.put("RCV_AMT", "반입량");
		map.put("RCV_B", "반입확인(BIB)");
		map.put("RCV_BIA_A", "BIA:반입확인등록(A:보세운송번호)");
		map.put("RCV_BIA_C", "BIA:반입확인등록(C:B/L번호)");
		map.put("RCV_BOC_CONFIRMATION", "반출확인");
		map.put("RCV_BONDED_AREA_MIW", "반입보세구역");
		map.put("RCV_C", "반입확인(BIC)");
		map.put("RCV_CBM", "반입용적");
		map.put("RCV_CNTR", "반입(컨테이너)");
		map.put("RCV_CONDITION", "반입상황");
		map.put("RCV_CONFIRMATION", "반입확인");
		map.put("RCV_CORRECTION", "반입정정");
		map.put("RCV_CORRECTION_LIST", "반입정정 리스트");
		map.put("RCV_CORRECTION_REQUEST", "반입정정신고");
		map.put("RCV_D", "반입확인(BID)");
		map.put("RCV_DATE", "반입일자");
		map.put("RCV_DATE_TIME", "반입일시");
		map.put("RCV_DIVIDE", "분할반입");
		map.put("RCV_EXPECT_MIW", "반입예정");
		map.put("RCV_EXPT", "반입예정");
		map.put("RCV_EXPT_CNTR", "반입예정(컨테이너)");
		map.put("RCV_EXPT_GENRL", "반입예정(일반)");
		map.put("RCV_GENRL", "반입(일반)");
		map.put("RCV_INVENTORY", "반입재고");
		map.put("RCV_LOC_PLACE", "반입장치장");
		map.put("RCV_MIW", "반입");
		map.put("RCV_NACCS_KIND", "반입식별");
		map.put("RCV_NO", "반입번호");
		map.put("RCV_PERSON", "반입자");
		map.put("RCV_PERSON_ADDR", "반입자 주소");
		map.put("RCV_PERSON_NM", "반입자 상호");
		map.put("RCV_PKG_QTY", "반입수량");
		map.put("RCV_PLACE", "반입장소");
		map.put("RCV_QTY", "반입개수");
		map.put("RCV_RATE_DOWN", "입고료 및 하차");
		map.put("RCV_REGIST", "반입신고");
		map.put("RCV_SEQ_NO", "반입번호 (순번)");
		map.put("RCV_SHIP_DATE", "입출고일");
		map.put("RCV_SHIP_DESC", "입/출고 내역");
		map.put("RCV_TIME", "반입시간");
		map.put("RCV_TRNS_NM", "반입운송자");
		map.put("RCV_TYPE", "반입구분");
		map.put("RCV_WT", "반입중량");
		map.put("RCV_YMD", "반입년월일");
		map.put("RCV_YYYY", "반입번호 (년도)");
		map.put("RE_PKG_CD", "재 포장단위");
		map.put("RE_PKG_NO", "재 포장번호");
		map.put("RE_PKG_QTY", "재포장개수");
		map.put("RE_PKG_RATE", "재포장료");
		map.put("RE_PKG_TYPE", "재포장 유형");
		map.put("REASON", "사고구분");
		map.put("REASON_MIW", "사유");
		map.put("RECEIPT_DATE", "접수일자");
		map.put("RECEIPT_INSURANCE", "보험영수증");
		map.put("RECEIVING_DATE", "입고일");
		map.put("RECEIVING_NO", "입고번호");
		map.put("RECEIVING_TERM", "입고기간");
		map.put("RECORD_BY", "작성자");
		map.put("RECORD_MIW", "작성");
		map.put("RECV_APPROVAL_DATE", "수신승인일자");
		map.put("RECV_COMP_NM", "인수회사명");
		map.put("RECV_DATE", "수신일자");
		map.put("RECV_DESC", "수신내용");
		map.put("RECV_DOC", "수신문서");
		map.put("RECV_NOTI_MIW", "접수통보");
		map.put("RECV_NOTICE", "수신구분");
		map.put("RECV_NOTICE_KIND", "수신종류");
		map.put("RECV_REASON", "거절사유");
		map.put("RECV_REMARK", "수신사유");
		map.put("REFUND", "환급");
		map.put("REGI", "등록");
		map.put("REGIST_DATE", "신고일자");
		map.put("RELEASE_CERTIFICATE", "출문증");
		map.put("REMARK", "비고");
		map.put("REMARK_1", "비고 1");
		map.put("REMARK_2", "비고 2");
		map.put("REMARK_3", "비고 3");
		map.put("REMARK_PERSON", "사유및담당자");
		map.put("REMARKs", "비고");
		map.put("REPORT_DATE", "전송일자");
		map.put("REPORT_FLG", "전송여부");
		map.put("REPORT_RESULT", "전송결과");
		map.put("REPORT_SEAL_DATE", "전송봉인일자");
		map.put("REPORT_STATUS", "전송상태");
		map.put("REPORT_TIME", "전송시간");
		map.put("REQ_DATE", "신청일자");
		map.put("REQ_NO", "신청번호");
		map.put("REQ_SEQ_NO", "신청번호 (순번)");
		map.put("REQ_TYPE", "신청구분");
		map.put("REQ_YYYY", "신청번호 (년도)");
		map.put("REQUEST_MIW", "요구사항");
		map.put("RESET", "초기화");
		map.put("RESIDENT_NO", "주민등록번호");
		map.put("RESIDUAL_CBM", "잔용적");
		map.put("RESIDUAL_QTY", "잔개수");
		map.put("RESIDUAL_WT", "잔중량");
		map.put("REVERT", "귀속");
		map.put("RMK_NO", "기호번호");
		map.put("RMK1", "비고1");
		map.put("RMK2", "비고2");
		map.put("RND_MIW", "반올림");
		map.put("RNDUP_MIW", "올림");
		map.put("ROW_NO", "행");
		map.put("ROWS", "건");
		map.put("RPT_DATE_AR_REG_INSR", "작성일자별 매출등록건 보험료");
		map.put("RPT_TYPE", "Report Type");
		map.put("RTON", "톤수");
		map.put("SALES_MAN", "영업사원");
		map.put("SALES_PRICE", "판매가");
		map.put("SAMPLE", "SAMPLE");
		map.put("SAND", "전송");
		map.put("SAT", "토");
		map.put("SAVE", "저장");
		map.put("SEA", "해상");
		map.put("SEA_INBND_MIW", "해상수입");
		map.put("SEA_OUTBND_MIW", "해상수출");
		map.put("SEAL_INSPECTION", "봉인검사");
		map.put("SEAL_NO", "봉인번호");
		map.put("SEAL_NO_1", "봉인 번호 1");
		map.put("SEAL_NO_2", "봉인 번호 2");
		map.put("SEAL_NO_3", "봉인 번호 3");
		map.put("SEAL_NO1", "봉인번호1");
		map.put("SEAL_NO2", "봉인번호2");
		map.put("SEAL_NO3", "봉인번호3");
		map.put("SEARCH", "조회");
		map.put("SECURITY_AMOUNT", "담보금");
		map.put("SECURITY_AMT", "전도금금액");
		map.put("SECURITY_AR_CONT", "담보대 매출내역");
		map.put("SECURITY_MIW", "증권");
		map.put("SECURITY_NO", "담보번호");
		map.put("SECURITY_SEQ_NO", "담보번호 (순번)");
		map.put("SECURITY_YYYY", "담보번호 (년도)");
		map.put("SELECT", "선택");
		map.put("SELLING", "SELLING");
		map.put("SEND_BACK", "반송");
		map.put("SEND_CBM", "발송용적");
		map.put("SEND_CNT", "발송개수");
		map.put("SEND_DATE", "전송일");
		map.put("SEND_MIW", "전송");
		map.put("SEND_RECV_RESULT", "송수신결과");
		map.put("SEND_WT", "발송중량");
		map.put("SEP", "9월");
		map.put("SEQ_MIW", "차수");
		map.put("SEQ_NO", "순번");
		map.put("SHED", "장치장소");
		map.put("SHIP", "반출");
		map.put("SHIP_AMT", "반출량");
		map.put("SHIP_C", "반출확인(BOC)");
		map.put("SHIP_CLASS", "반출구분");
		map.put("SHIP_CORRECTION_LIST", "반출정정 리스트");
		map.put("SHIP_CORRECTION_REQUEST", "반출정정신고");
		map.put("SHIP_DATE", "반출일자");
		map.put("SHIP_DATE_TIME", "반출일시");
		map.put("SHIP_DIVIDE_DIFF", "분할반출로 인한 차이");
		map.put("SHIP_EST_NOTICE01_MIW", "1:반출예정통고");
		map.put("SHIP_EST_NOTICE02_MIW", "2:반출명령통고");
		map.put("SHIP_INFO", "출고사항");
		map.put("SHIP_INPUT_MIW", "반출입력");
		map.put("SHIP_ITEM_SEQ_NO", "반출품목순번");
		map.put("SHIP_MARK", "Shipping Mark");
		map.put("SHIP_ME", "반출용적");
		map.put("SHIP_NO", "반출번호");
		map.put("SHIP_NO_DESC", "내국물품이 D 일경우");
		map.put("SHIP_NOTICE", "반출통고");
		map.put("SHIP_ORDERER", "출고지시자");
		map.put("SHIP_PERSON", "출고담당자");
		map.put("SHIP_PKG_QTY", "반출수량");
		map.put("SHIP_PLACE", "반출지");
		map.put("SHIP_QTY", "출고수량");
		map.put("SHIP_RATE_UP", "출고료 및 상차");
		map.put("SHIP_REGIST", "반출신고");
		map.put("SHIP_REGIST_DATE", "반출신고기한");
		map.put("SHIP_RPT", "출고보고서");
		map.put("SHIP_SEQ_NO", "반출번호 (순번)");
		map.put("SHIP_TIME", "반출시간");
		map.put("SHIP_TYPE", "운송유형");
		map.put("SHIP_UP", "출고상차");
		map.put("SHIP_UP_FRT_CD", "출고상차 운임코드");
		map.put("SHIP_WT", "반출중량");
		map.put("SHIP_YMD", "물품출고월일");
		map.put("SHIP_YN", "반출여부");
		map.put("SHIP_YYYY", "반출번호 (년도)");
		map.put("SHIPPER_MIW", "Shipper");
		map.put("SHIPPING_APPROVAL", "반출승인");
		map.put("SHIPPING_CORRECTION_MIW", "반출정정");
		map.put("SHIPPING_DATE", "출고일");
		map.put("SHIPPING_POINT", "적출지");
		map.put("SHIPPING_PRINT", "물품반출증");
		map.put("SHP_A", "반출확인(BOA)");
		map.put("SHPR_ADDR", "화주주소");
		map.put("SHPR_ADDR_1", "송하인주소1");
		map.put("SHPR_ADDR_2", "송하인주소2");
		map.put("SHPR_ADDR_3", "송하인주소3");
		map.put("SHPR_CD", "송하인코드");
		map.put("SHPR_CODE", "화주코드");
		map.put("SHPR_ID", "화주");
		map.put("SHPR_NAME", "화주명");
		map.put("SHPR_NM", "송하인명");
		map.put("SHPR_NM_EN", "송하인명(영문)");
		map.put("SHPR_NM_KO", "송하인명(한글)");
		map.put("SHPR_PRESIDENT", "대표자");
		map.put("SHPR_RESIDENT", "송하인 사업자번호");
		map.put("SHPR_RESIDENT_NO", "사업자번호");
		map.put("SHPR_TEL", "송하인 전화번호");
		map.put("SHPR_ZIP", "송하인 우편번호");
		map.put("SIGN", "서명");
		map.put("SIGN_BY", "접수자");
		map.put("SIMT_SHIP", "선적반출");
		map.put("SMS_RECEIPT_NO", "SMS수신번호");
		map.put("SMS_RECIPIENT", "SMS수신인");
		map.put("SORT", "정렬");
		map.put("SORT_NO", "정렬순번");
		map.put("SPACE_A", "A");
		map.put("SPACE_B", "B");
		map.put("SPACE_C", "C");
		map.put("SPACE_D", "D");
		map.put("SPACE_E", "E");
		map.put("SPACE_F", "F");
		map.put("SPACE_G", "G");
		map.put("SPACE_H", "H");
		map.put("SPECIAL_1", "특수화물 1");
		map.put("SPECIAL_2", "특수화물 2");
		map.put("SPECIAL_3", "특수화물 3");
		map.put("SPECIAL_CLASS", "특수구분");
		map.put("STAIR_NO", "단");
		map.put("STAMP", "인");
		map.put("STANDARD", "규격");
		map.put("START_DATE", "시작일자");
		map.put("STATUS", "상태");
		map.put("STOCK_AMT", "재고량");
		map.put("STORAGE_AMOUNT", "보관료공급가액");
		map.put("STORAGE_CALC_WT", "보관료계산중량");
		map.put("STORAGE_CUST_TYPE", "보관료요율협력관계");
		map.put("STORAGE_DAY", "보관일(수)");
		map.put("STORAGE_DC", "보관료할인%");
		map.put("STORAGE_EXTRA", "보관료할증%");
		map.put("STORAGE_FREE_DAY", "보관료면제보관일수");
		map.put("STORAGE_LIMIT_WT", "보관료하한적용중량");
		map.put("STORAGE_RATE", "보관료");
		map.put("STORAGE_RATE_SUM", "보관료 합계");
		map.put("STORAGE_VAT", "보관료세액");
		map.put("STORAGE_WON_ROUND", "보관료원단위");
		map.put("STORE", "수납");
		map.put("STORE_TOTAL", "수납총계");
		map.put("STORY_NO", "층");
		map.put("STRG_CUST_TYPE", "거래처구분");
		map.put("STRG_DC", "보관료할인");
		map.put("STRG_EXTRA", "보관료할증");
		map.put("STRG_FREE_DAY", "보관료면제일수");
		map.put("STRG_INVOICE_RATE", "보관료명세서");
		map.put("STRG_LIMT_WT", "보관료하한적용중량");
		map.put("STRG_MODIFY", "보관료조정");
		map.put("STRG_RATE_TOTAL", "보관료총계");
		map.put("STRG_WON_RND", "운송료원단위");
		map.put("SUBJECT_MIW", "제목");
		map.put("SUBSCRIP_DATE", "청약일자");
		map.put("SUBTOTAL", "소계");
		map.put("SUM_AMT", "금");
		map.put("SUN", "일");
		map.put("SYS_CD", "시스템코드");
		map.put("SYSOP", "운영인");
		map.put("TARGET_CD", "대상코드");
		map.put("TARGET_CODE", "대상코드");
		map.put("TARGET_FIELD", "대상필드");
		map.put("TAX_DATE", "계산서일자");
		map.put("TAX_EXEM_BSNS", "면세사업");
		map.put("TAX_NO", "계산서번호");
		map.put("TAX_TYPE", "계산서구분");
		map.put("TAXPATER", "납세자성명");
		map.put("TAXPATER_NO", "납세번호");
		map.put("TAXPAYER", "납세의무자");
		map.put("TAXPAYER_NM", "납세자명");
		map.put("TEL", "전화번호");
		map.put("TEMS", "조건");
		map.put("TERM", "기간");
		map.put("TEST_NO", "123");
		map.put("THC_BAS_AMT", "THC료기본금액");
		map.put("THC_BASIC_AMT", "THC료기본금액");
		map.put("THC_CALC_WT", "THC료계산중량");
		map.put("THC_DC", "THC료할인%");
		map.put("THC_EXTRA_AMT", "THC료할증단가");
		map.put("THC_FRT_CD", "공항료 운임코드");
		map.put("THC_RATE", "공항료");
		map.put("THC_WON_RND", "THC료원단위");
		map.put("THC_WON_ROUND", "THC료원단위");
		map.put("THIS_MONTH", "이번달");
		map.put("THIS_MONTH_INVENTORY", "금월 재고");
		map.put("THIS_MONTH_RCV", "본월반입");
		map.put("THIS_MONTH_SHIP", "본월반출");
		map.put("THU", "목");
		map.put("TITLE", "Title");
		map.put("TO_WH_CD", "이고창고코드");
		map.put("TODAY_SHIP_CBM", "금일출고용적");
		map.put("TODAY_SHIP_QTY", "금일출고수량");
		map.put("TODAY_SHIP_WT", "금일출고중량");
		map.put("TOT_ALLOC_CBM", "총할당용적");
		map.put("TOT_ALLOC_QTY", "총할당수량");
		map.put("TOT_ALLOC_WT", "총할당중량");
		map.put("TOT_MIW", "합산");
		map.put("TOT_SEQ", "전체차수");
		map.put("TOTAL", "총계");
		map.put("TOTAL_AMT", "총금액");
		map.put("TOTAL_CBM", "총용적");
		map.put("TOTAL_QTY", "총수량");
		map.put("TOTAL_RATE", "계");
		map.put("TOTAL_SUM", "합계");
		map.put("TOTAL_WT", "총중량");
		map.put("TRACKING_DATE", "화물추적일자");
		map.put("TRACKING_NO", "화물추적번호");
		map.put("TRACKING_STATUS", "화물추적상태");
		map.put("TRACKING_TIME", "화물추적시간");
		map.put("TRADE_TYPE_MIW", "Trade Type");
		map.put("TRANS_BAS_AMT", "운송료기본금액");
		map.put("TRANS_BASIC_AMT", "운송료기본금액");
		map.put("TRANS_CALC_WT", "운송료계산중량");
		map.put("TRANS_DC", "운송료할인%");
		map.put("TRANS_EXTRA_AMT", "운송료할증단가");
		map.put("TRANS_MIW", "회계이관");
		map.put("TRANS_NO", "회계이관번호");
		map.put("TRANS_RATE", "이적료");
		map.put("TRANS_WON_ROUND", "운송료원단위");
		map.put("TRANSFER_RATE", "운송료");
		map.put("TRANSPORT_RATE", "이송료");
		map.put("TREASURY", "국고");
		map.put("TREASURY_REVERT", "국고 귀속");
		map.put("TRNS_BAS_AMT", "운송료기본금액");
		map.put("TRNS_CD", "운송사코드");
		map.put("TRNS_DATE", "운송기한");
		map.put("TRNS_DC", "운송료할인");
		map.put("TRNS_ETC", "운송회사등");
		map.put("TRNS_EXTRA_AMT", "운송료할증단가");
		map.put("TRNS_FRT_CD", "운송 운임코드");
		map.put("TRNS_INVOICE_RATE", "운송료명세서");
		map.put("TRNS_MIW", "운송사");
		map.put("TRNS_NM", "운송사명");
		map.put("TRUCK_NO", "차량 번호");
		map.put("TS_YN", "경유지(입고유형)");
		map.put("TUE", "화");
		map.put("TYPE_MIW", "구분");
		map.put("UN_RCV_MIW", "미반입");
		map.put("UNAPLY_BATCH", "일괄반영안함");
		map.put("UNAPPROVED_AMT", "미승인량");
		map.put("UNATTENDED_YN", "미처리");
		map.put("UNDER", "미만");
		map.put("UNISSUED", "미발행");
		map.put("UNIT", "단위");
		map.put("UNSETTLED_MIW", "미정산");
		map.put("UNSHIPPING", "미반출");
		map.put("UP_DATE", "수정일자");
		map.put("UP_PERSON", "수정자");
		map.put("UP_TIME", "수정시간");
		map.put("USE_ALL", "전체");
		map.put("USE_DATE_FROM", "사용시작일자");
		map.put("USE_DATE_TO", "사용종료일자");
		map.put("USE_GUBUN", "사용구분");
		map.put("USE_N", "미사용");
		map.put("USE_TYPE", "용도구분");
		map.put("USE_Y", "사용");
		map.put("USE_YN", "사용여부");
		map.put("USED", "구분");
		map.put("USER_COL", "사용자칼럼");
		map.put("VALUE", "값");
		map.put("VALUE_TYPE", "표기구분");
		map.put("VAT", "부가세");
		map.put("VAT_RATE", "부가세율");
		map.put("VAT_TOTAL", "부가가치 계");
		map.put("VENDOR", "판매자");
		map.put("VENDOR_ID", "판매자 ID");
		map.put("VENDOR_NM", "판매자명");
		map.put("VESSEL", "선박");
		map.put("VESSEL_VOY", "VESSEL/VOY");
		map.put("VOYAGE_NO", "항차");
		map.put("VSL_FLIGHT_NM", "선기명");
		map.put("VSL_NM", "선명");
		map.put("WED", "수");
		map.put("WELCOME_BY", "님 환영합니다.");
		map.put("WH_AMOUNT", "창고료공급가액");
		map.put("WH_BOSS", "창고장");
		map.put("WH_CD", "창고코드");
		map.put("WH_GMP", "김포창고");
		map.put("WH_GRADE_TYPE", "창고등급 구분");
		map.put("WH_INVOICE_RATE", "창고료명세서");
		map.put("WH_NM", "창고명");
		map.put("WH_NO", "창고NO");
		map.put("WH_PUS", "부산창고");
		map.put("WH_RATE", "창고료");
		map.put("WH_RATE_TOTAL", "창고료계");
		map.put("WH_SEL", "서울창고");
		map.put("WH_TOTAL_AMOUNT", "창고료합계액");
		map.put("WH_VAT", "창고료세액");
		map.put("WHMV_ETC", "이고기타");
		map.put("WIDTH", "폭");
		map.put("WIDTH_MIW", "세로");
		map.put("WON", "원");
		map.put("WORD_ID", "명칭ID");
		map.put("WORK_DATE", "작업일자");
		map.put("WORK_DATETIME", "작업일시");
		map.put("WORK_DESC", "작업구분");
		map.put("WORK_TIME", "작업일시");
		map.put("WORKER", "작업자");
		map.put("WT", "중량");
		map.put("WT_MRN", "총중량");
		map.put("WT_REASON", "사고중량");
		map.put("WT_ROUND", "중량(KG) 올림");
		map.put("WT_UNIT", "총중량단위");
		map.put("XLS", "엑셀");
		map.put("XRAY_GUBUN", "XRAY구분");
		map.put("XRAY_VALUE_CHANGE", "XRAY속성변경");
		map.put("YEAR", "년");
		map.put("YEAR_IO_CCD_EXC_STAT", "년간 수출입반출입현황");
		map.put("YES", "예");
		map.put("ZONE_CD", "존");
		return map;
	}
}
